### ISSUE TITLE
Github Workflow error 

### ISSUE THREAD

**Issue by Stephane-Pires** [saleem/tdd-book-code#2]
Hi, 

First of all thank you for helping wrapping my head around the TDD concepts. I think your book is a good resources to start on the subject. 

I have been running into an error at the chapter 13. 

![Capture d’écran 2022-08-28 à 11 24 48](https://user-images.githubusercontent.com/52931491/187067185-090da3fb-f0ab-4d7e-b63b-1061949d054b.png)

For now i have been unable to understand what's wrong. I'm not accustomed to configure YAML files & Github actions. 

Any idea on what could be wrong ? 

I have already tried :  

- upgrade actions/checkout@v2  ----> action/checkout@v3
- modify the platform on which the CI runs
- manually set the path

But all of theses have been blind shots. 

If you're available to help : here the repository https://github.com/Stephane-Pires/tdd-project

**Comment by saleem** [comment]
Hi, @Stephane-Pires:

1. I cannot access your Github repo. (Is it private?)
2. The `Cannot find module` error happens when some JS module cannot be found. For 3rd party modules, this _usually_ means your `node_modules` folder has become wonky. *However, this doesn't appear to be the case here.*
3. Since your error states that the `test_money.js` file cannot be found, I'd recommend double checking your file and folder structure.
4. In particular: the error shows that the file was searched in the `.../tdd-project/tdd-project/js` folder. Is this correct? The repeated folder name looks fishy -- it's certainly not the naming convention used in the book.
5. I did run the CI build for the JS code on the canonical repository (https://github.com/saleem/tdd-book-code) and it is green. 
6. I'd recommend cloning the canonical repository in a different root folder and then doing something like `diff -r /path/to/canonical/tdd-book-code /path/to/your/clone/of/tdd-book-code`. Any differences you see may give you a (better) clue.

Best of luck. And **thank you** for reading and following the book!

**Comment by Stephane-Pires** [comment]
Grrr, i did find the mistake. 

It was a typo  i renamed `test_money` to `test-money`. 

Following the book i didn't updated the file `js.yml` accordingly. 

Thanks you for your fast answer. I hope you didn't loose to much time answering me. 

All is green on my side now. 

Bye bye @saleem your book definitely introduced me to TDD !

**Comment by saleem** [comment]
Glad you found and fixed the error, @Stephane-Pires! 
All the best.
